kind: List
apiVersion: v1
items:

- apiVersion: v1
  kind: OAuthClient
  metadata:
    labels:
      logging: kopf-proxy
    name: kopf-proxy
  redirectURIs:
  - https://proxy.ec2-54-234-85-63.compute-1.amazonaws.com
  respondWithChallenges: false
  secret: e7229c26ddf3fd2588dd6fdd2b5e56fa122416b39b1b21ea2944b7463de96cf5
  allowAnyScope: true
  # scopeRestrictions:
  # - literals:
  #   - user:info
  #   - user:check-access
  #   - user:list-projects

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: proxy
    labels:
      logging: kopf-proxy
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"proxy"}}'

# - apiVersion: authorization.openshift.io/v1
#   kind: ClusterRoleBinding
#   metadata:
#     name: proxy-cluster-reader
#   roleRef:
#     name: cluster-reader
#   subjects:
#   - kind: ServiceAccount
#     name: proxy
#     namespace: logging

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: proxy
    labels:
      logging: kopf-proxy
  spec:
    host: proxy.ec2-54-234-85-63.compute-1.amazonaws.com
    to:
      name: proxy
    tls:
      termination: Reencrypt

- apiVersion: v1
  kind: Service
  metadata:
    name: proxy
    labels:
      logging: kopf-proxy
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: proxy-tls
  spec:
    ports:
    - name: proxy
      port: 443
      targetPort: 8443
    selector:
      logging: kopf-proxy

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      logging: kopf-proxy
      component: kopf-proxy
      logging-infra: kopf-proxy
      provider: openshift
    name: logging-kopf-proxy
  spec:
    replicas: 1
    selector:
      component: kopf-proxy
      logging-infra: kopf-proxy
      provider: openshift
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          logging: kopf-proxy
          component: kopf-proxy
          logging-infra: kopf-proxy
          provider: openshift
        name: logging-kopf-proxy
      spec:
        serviceAccountName: proxy
        containers:
        - name: kopf-proxy
          image: openshift/oauth-proxy:v1.0.0
          imagePullPolicy: Always
          args:
          - --https-address=:8443
          - -provider=openshift
          - -client-id=kopf-proxy
          - -client-secret=e7229c26ddf3fd2588dd6fdd2b5e56fa122416b39b1b21ea2944b7463de96cf5
          - -upstream=http://kopf:8080
          # - '-openshift-sar={"namespace": "logging", "verb": "edit", "resource": "pods"}'
          # - '-openshift-sar={"namespace": "default", "verb": "edit", "resource": "deploymentconfig"}'
          - --tls-cert=/etc/tls/private/tls.crt
          - --tls-key=/etc/tls/private/tls.key
          - --cookie-secret=e7229c26ddf3fd2588dd6fdd2b5e56fa
          - -pass-access-token
          - -ssl-insecure-skip-verify=true
          volumeMounts:
          - mountPath: /etc/tls/private
            name: proxy-tls
          ports:
          - containerPort: 8443
            name: kopf-proxy
            protocol: TCP
          resources:
            limits:
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        volumes:
        - name: proxy-tls
          secret:
            secretName: proxy-tls
    test: false
    triggers:
    - type: ConfigChange
